# This file relates to internal XMOS infrastructure and should be ignored by external users
---
lib_name: lib_xua
project: '{{lib_name}}'
title: '{{lib_name}}: USB Audio components library'
version: 5.1.0

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  substitutions_path: doc/substitutions.inc
  root_doc: doc/rst/lib_xua.rst
  linkcheck_ignore_regex: ['.*']
  cognidox_part_number: XM-012296-UG
  doxygen_projects:
    lib_xua:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/rst/lib_xua.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{lib_name}}_v{{version}}'
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{lib_name}}_v{{version}}_readme'
      pdf_short: yes
software:
  cognidox_part_number: XM-012639-SM
