an_number: AN00248
project: '{{an_number}}'
title: '{{an_number}}: Using lib_xua with lib_mic_array'
version: 1.0.0

documentation:
  substitutions_path: doc/substitutions.inc
  exclude_patterns_path: doc/exclude_patterns.inc
  root_doc: doc/rst/AN00248_xua_example_pdm_mics.rst
  cognidox_part_number: XM-013123-AN
  pdfs:
    doc/rst/AN00248_xua_example_pdm_mics.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{an_number}}_v{{version}}'
      pdf_short: yes
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{an_number}}_v{{version}}_readme'
      pdf_short: yes
